### PR TITLE
chore: update dependecies

### PR DESCRIPTION
**Pull request by dalyr95**
Same as https://github.com/motorway/motorway-ui-test/pull/49/files without the readme update, this will hopefully kill the million dependabot PRs. Tested locally and works as expected.

### CODE REVIEW

**Comment by dalyr95** [comment]
Context on nth-check https://stackoverflow.com/questions/71282206/github-dependabot-alert-inefficient-regular-expression-complexity-in-nth-check

**Review by kml1990 — COMMENTED** [review]
Shall we close considering that are moving to Vite?

**Comment by dalyr95** [comment]
> Shall we close considering that are moving to Vite?

Let's just close the DB PRs first.

**Review by szympajka — APPROVED** [review]
works :)

**Review by kml1990 — APPROVED** [review]
Works for me too 👍

**Pull request merged**
